official_domains:
  flesh-and-blood:
    - fabtcg.com

  magic:
    - magic.wizards.com
    - wizards.com
    - cnwizards.com

  pokemon:
    - pokemon.com
    - pokemon-card.com
    - pokemon.cn

  sorcery:
    - sorcerytcg.com

  naruto:
    - naruto-cardgame.com

  one-piece:
    - onepiece-cardgame.com

  star-wars-unlimited:
    - starwarsunlimited.com
    - fantasyflightgames.com

  riftbound:
    - playriftbound.com
    - riotgames.com

  digimon:
    - world.digimoncard.com
    - digimoncard.com

  yugioh:
    - yugioh-card.com
    - yu-gi-oh.jp
    - konami.com

  lorcana:
    - disneylorcana.com
    - ravensburger.com
